### ISSUE TITLE
Extension is not loaded

### ISSUE THREAD

**Issue by gerroon** [RemiRigal/Yape#1]
Hi

I am using Chromium 92 Ungoogled , I install it with "load unpacked" It says it is loaded but I do not see Yape anywere, it is not in the extension browser nor in the tabs. Is it installing as another name?

Edit

Hmm, it is installed as Pyload Assistant, but why call it Yape?

**Comment by RemiRigal** [comment]
Hi @gerroon, thank you for posting an issue.

Indeed, the project was initially called PyLoad Assistant but during the renaming process I forgot to update the manifest. I've made a commit to fix that, the extension should be called `Yape` now.
