### ISSUE TITLE
Firefox Addon not Available

### ISSUE THREAD

**Issue by LazyGeniusMan** [RemiRigal/Yape#10]
Hi, looks like Firefox addon is unavailable
![image](https://user-images.githubusercontent.com/58850480/150675415-42901233-0cad-4357-95c9-4f12d60b4b35.png)

What happen to firefox addon?

**Comment by RemiRigal** [comment]
Thank you for the issue, I'm working on it, the addon should be back soon !

**Comment by RemiRigal** [comment]
Hi @LazyGeniusMan, the extension is back on the Firefox add-ons page !
