### ISSUE TITLE
how to configure with a seedbox

### ISSUE THREAD

**Issue by nerv-nc** [RemiRigal/Yape#11]
Hi!
I'm trying to configure Yape with a seedbox.... but seems I do something in wrong way everytime.
Are seedbox allowed?
e.g. mine is https://star.seedhost.eu/username/pyload

thanks!

**Comment by RemiRigal** [comment]
Hi @nerv-nc, thank you for opening an issue !
Currently you can only configure a host/port for your PyLoad instance, it does not support specific paths on top of that (like `username/pyload` in you case). I will add this to the configuration page !

**Comment by nerv-nc** [comment]
thanks for the quick reply @RemiRigal!
hope one day can be possible to support

have a nice day :)

**Comment by nerv-nc** [comment]
Hello @RemiRigal, what a wonderful news!
Thanks a lot for the effort in adding this enhancement and sharing it!

I have tried using Yape with this feature, but I think there is still something I am doing wrong:
- if I don't put the server port I get a notification like "Not granting this permission will make the extension unusable." and the login fails, without reporting errors or anything else
- I tried putting as port the same one present on pyLoad (config -> general -> remote ->port), I don't get the notification but the login fails, without reporting errors or anything else
- I tried with port 443 and I have the same behavior

if you have time for any suggestions, it would be very welcome and appreciated :)

thank you and have a great weekend!

**Comment by RemiRigal** [comment]
Thank you for your feedback, the message you got when removing entirely the port is actually a bug, you should always provide a port. I will work on the form validation to prevent this.

If you want to configure the URL you mentioned earlier (https://star.seedhost.eu/username/pyload), you need to have the following configuration:
- Host: star.seedhost.eu
- Port: 443 (default port for HTTPS, would be 80 for HTTP)
- Path: /username/pyload
- HTTPS: checked

You should be able to see the complete URL at the bottom of the form, if it's the case you can click the `Save` button.

Then there are two possibilities:
- You have a `You are logged in` message: you are all set :)
- You have a  `You are not logged in` message: you must log in or the server is unreachable

I've just published an improved version `v1.1.1` of the extension that should be available in the next few hours. This version is more explicit on the type of error you are getting. Can you try again with this version and let me know ? Thank you !

**Comment by RemiRigal** [comment]
FYI, version `v1.1.1` is available already !

**Comment by nerv-nc** [comment]
Good morning @RemiRigal!
Many thanks for the support, it works wonderfully :)
