### ISSUE TITLE
FR: Right click Youtube  url support

### ISSUE THREAD

**Issue by gerroon** [RemiRigal/Yape#2]
Hi

It would be nice if this addon can be access over right click menu when clicked on a video link like Youtube links so that one can easily pass those urls to PyLoad.

thanks

**Comment by RemiRigal** [comment]
Hi @gerroon, thank you for the suggestion I will work on it !

**Comment by RemiRigal** [comment]
Hi @gerroon, I just pushed an update that adds context menu downloads, let me know if it meets your expectations !

**Comment by gerroon** [comment]
Hi

I have been waiting for the extension store version to test it. Does it look like it is going to take some time to get there?
