### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by hhergeth** [RemiRigal/Yape#5]
I tried setting up Yape but ran into the following error message:
`Login failed, server unreachable`

On the first page of the setup process I entered the url of my pyload instance. It is *not* locally hosted, it is on a different machine.
I had a look at the developer tab in Chrome and saw this request
![yape-login-error](https://user-images.githubusercontent.com/4276605/137179791-edf7c2e1-858b-498f-8606-eb2171a72cda.png)

This is somewhat puzzling since there is no hope to reach pyload there.

**Comment by hhergeth** [comment]
Excellent remote debugging skills!
You were spot on and it works now : )

Maybe one more comment: I had to be somewhat careful with how I entered the url:

- When I had a https:// at the beginning there would be two of these in the queries sent.
- When I had a trailing / at the end the login query would go to blabla.blub/:433/

After removing these it works flawlessly though

**Comment by milahu** [comment]
still a bug in yape

fixed by changing host from 127.0.0.1 to localhost

this seems to force some state update
